package main

var objects = []string{
	"un caleçon",
	"un film",
	"une grenouille",
	"une serpilliere",
	"une brosse à dent",
	"une baleine",
	"un phoque",
	"un poulet",
	"un clavier",
	"un container",
	"un poulpe",
	"une souris",
	"une chaussette",
	"une batterie",
	"un piano",
	"une flûte à bec",
	"un biniou",
	"une conférence",
	"une piñata",
	"un écran",
	"un camion",
	"un bateau",
	"un seau",
	"une paire de lunette",
	"un monocle",
}
