package main

var verbs = []string{
	"j'entère",
	"je tourne",
	"j'avance vers",
	"je regarde",
	"j'invoque",
	"j'espionne",
	"je contourne",
	"je m'assois sur",
	"je mange",
	"je pousse",
	"je bouscule",
	"je range",
	"j'observe",
	"je marche sur",
	"j'endors",
	"je tape sur",
	"je programme",
	"je digère",
	"j'embrasse",
	"je déneige",
	"je rebondis sur",
	"je convoque",
	"je découpe",
	"j'asperge",
	"je chevauche",
	"je forge",
	"j'insulte",
	"je dépanne",
	"j'enquête sur",
	"je monte sur",
	"je malaxe",
	"je sirote",
	"j'examine",
	"je fais rôtir",
	"je loue",
	"je photocopie",
	"je cuisine",
}
