package kamoulox

var objects = []string{
	"un caleçon",
	"un film",
	"une grenouille",
	"une serpilliere",
	"une brosse à dent",
	"une baleine",
	"un phoque",
	"un poulet",
	"un clavier",
	"un container",
	"un poulpe",
	"une souris",
	"une chaussette",
	"une batterie",
	"un piano",
	"une flûte à bec",
	"un biniou",
	"une conférence",
	"une piñata",
	"un écran",
	"un camion",
	"un bateau",
	"un seau",
	"une paire de lunette",
	"un monocle",
	"un clown",
	"un programmeur",
	"une startup",
	"un lavabo",
	"un barbare",
	"un panneau publicitaire",
	"un marchepied",
	"un palmier",
	"un échelle",
	"une crevette",
	"une chouette",
	"un lampadaire",
	"un tournevis",
	"un orchestrateur",
	"un chat",
	"un chien",
	"un tigre",
	"un lion",
	"un hippopotame",
	"une autruche",
	"Nana Mouskouri",
	"Francis Lalane",
	"Britney Spears",
	"Maitre Gimms",
	"Barack Obama",
	"Austin Powers",
	"Clint Eastwood",
	"Danny Boon",
	"Donald Trump",
	"un marteau",
	"une enclume",
	"une boîte à outils",
	"un dragon",
	"une lampe torche",
	"une tarte aux pommes",
	"un pingouin",
	"un panda",
	"un yaourt",
	"une cuillère",
	"une peluche",
	"un frisbee",
	"un ballon de foot",
	"une raquette de tennis",
	"un parasol",
	"une chaise longue",
	"un extincteur",
	"un thermos",
	"un sac à dos",
	"une boussole",
	"un vélo",
	"un parapluie",
	"une machine à écrire",
	"un robot",
	"un hologramme",
	"une éponge",
	"un coussin",
	"un tapis volant",
	"un chapeau melon",
	"un fauteuil roulant",
}
