package kamoulox

var objects = []string{
	"un caleçon",
	"un film",
	"une grenouille",
	"une serpilliere",
	"une brosse à dent",
	"une baleine",
	"un phoque",
	"un poulet",
	"un clavier",
	"un container",
	"un poulpe",
	"une souris",
	"une chaussette",
	"une batterie",
	"un piano",
	"une flûte à bec",
	"un biniou",
	"une conférence",
	"une piñata",
	"un écran",
	"un camion",
	"un bateau",
	"un seau",
	"une paire de lunette",
	"un monocle",
	"un clown",
	"un programmeur",
	"une startup",
	"un lavabo",
	"un barbare",
	"un panneau publicitaire",
	"un marchepied",
	"un palmier",
	"un échelle",
	"une crevette",
	"une chouette",
	"un lampadaire",
	"un tournevis",
	"un orchestrateur",
	"un chat",
	"un chien",
	"un tigre",
	"un lion",
	"un hippopotame",
	"une autruche",
	"Nana Mouskouri",
	"Francis Lalane",
	"Britney Spears",
	"Maitre Gimms",
	"Barack Obama",
	"Austin Powers",
	"Clint Eastwood",
	"Danny Boon",
	"Donald Trump",
}
