package kamoulox

var verbs = []string{
	"j'enterre",
	"je tourne",
	"j'avance vers",
	"je regarde",
	"j'invoque",
	"j'espionne",
	"je contourne",
	"je m'assois sur",
	"je mange",
	"je pousse",
	"je bouscule",
	"je range",
	"j'observe",
	"je marche sur",
	"j'endors",
	"je tape sur",
	"je programme",
	"je digère",
	"j'embrasse",
	"je déneige",
	"je rebondis sur",
	"je convoque",
	"je découpe",
	"j'asperge",
	"je chevauche",
	"je forge",
	"j'insulte",
	"je dépanne",
	"j'enquête sur",
	"je monte sur",
	"je malaxe",
	"je sirote",
	"j'examine",
	"je fais rôtir",
	"je loue",
	"je photocopie",
	"je cuisine",
	"je code",
	"je deploie",
	"je compile",
	"je debug",
	"je teste",
	"je decompile",
	"je documente",
	"je design",
	"je jauge",
	"je dessine",
	"je teleporte",
	"j'observe",
	"je grimpe sur",
	"je nage dans",
	"je m'accroche à",
	"je collectionne",
	"je jongle avec",
	"je lance",
	"je détruis",
	"je fabrique",
	"je peins",
	"je sculpte",
	"je rampe sous",
	"je médite sur",
	"je capture",
	"je délivre",
	"je rends hommage à",
	"je déplace",
	"je souffle sur",
	"je contemple",
	"je secoue",
	"je ralentis",
	"je répare",
	"je rassemble",
	"je déterre",
	"je construis",
	"je m'envole avec",
	"je réchauffe",
	"je refroidis",
	"je protège",
	"je remixe",
	"je réinvente",
}
