name: Docker Image CI

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Creating Docker Image Labels
      id: meta
      uses: docker/metadata-action@v4
      with:
         images: |
            jeanlaurent/kamoulox
         tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable=${{ endsWith(GitHub.ref, 'master') }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          sbom: true
          provenance: mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

